apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellopy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellopy
  template:
    metadata:
      labels:
        app: hellopy
    spec:
      containers:
      - name: hellopy
        image: gcr.io/amplified-lamp-384112/hello:1.0.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hellopy-service
spec:
  type: LoadBalancer
  selector:
    app: hellopy
  ports:
  - port: 50
    targetPort: 3000
